//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.1-12/20/2010 05:40 PM(foreman)-)
//


package com.odfl.time;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.odfl.time package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetTT_QNAME = new QName("http://time.odfl.com/", "getTT");
    private final static QName _GetTTResponse_QNAME = new QName("http://time.odfl.com/", "getTTResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.odfl.time
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TimeRequest }
     * 
     */
    public TimeRequest createTimeRequest() {
        return new TimeRequest();
    }

    /**
     * Create an instance of {@link GetTTResponse }
     * 
     */
    public GetTTResponse createGetTTResponse() {
        return new GetTTResponse();
    }

    /**
     * Create an instance of {@link TimeResponse }
     * 
     */
    public TimeResponse createTimeResponse() {
        return new TimeResponse();
    }

    /**
     * Create an instance of {@link GetTT }
     * 
     */
    public GetTT createGetTT() {
        return new GetTT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://time.odfl.com/", name = "getTT")
    public JAXBElement<GetTT> createGetTT(GetTT value) {
        return new JAXBElement<GetTT>(_GetTT_QNAME, GetTT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTTResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://time.odfl.com/", name = "getTTResponse")
    public JAXBElement<GetTTResponse> createGetTTResponse(GetTTResponse value) {
        return new JAXBElement<GetTTResponse>(_GetTTResponse_QNAME, GetTTResponse.class, null, value);
    }

}
