//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.1-12/20/2010 05:40 PM(foreman)-)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://time.odfl.com/")
package com.odfl.time;
