//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.1-12/20/2010 05:40 PM(foreman)-)
//


package com.odfl.time;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "TimeLookupService", targetNamespace = "http://time.odfl.com/", wsdlLocation = "META-INF/wsdl/TimeLookupService.wsdl")
public class TimeLookupService
    extends Service
{

    private final static URL TIMELOOKUPSERVICE_WSDL_LOCATION;
    private final static WebServiceException TIMELOOKUPSERVICE_EXCEPTION;
    private final static QName TIMELOOKUPSERVICE_QNAME = new QName("http://time.odfl.com/", "TimeLookupService");

    static {
            TIMELOOKUPSERVICE_WSDL_LOCATION = com.odfl.time.TimeLookupService.class.getResource("/META-INF/wsdl/TimeLookupService.wsdl");
        WebServiceException e = null;
        if (TIMELOOKUPSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/TimeLookupService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TIMELOOKUPSERVICE_EXCEPTION = e;
    }

    public TimeLookupService() {
        super(__getWsdlLocation(), TIMELOOKUPSERVICE_QNAME);
    }

    public TimeLookupService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIMELOOKUPSERVICE_QNAME, features);
    }

    public TimeLookupService(URL wsdlLocation) {
        super(wsdlLocation, TIMELOOKUPSERVICE_QNAME);
    }

    public TimeLookupService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIMELOOKUPSERVICE_QNAME, features);
    }

    public TimeLookupService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TimeLookupService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TimeLookupDelegate
     */
    @WebEndpoint(name = "TimeLookupPort")
    public TimeLookupDelegate getTimeLookupPort() {
        return super.getPort(new QName("http://time.odfl.com/", "TimeLookupPort"), TimeLookupDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimeLookupDelegate
     */
    @WebEndpoint(name = "TimeLookupPort")
    public TimeLookupDelegate getTimeLookupPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://time.odfl.com/", "TimeLookupPort"), TimeLookupDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIMELOOKUPSERVICE_EXCEPTION!= null) {
            throw TIMELOOKUPSERVICE_EXCEPTION;
        }
        return TIMELOOKUPSERVICE_WSDL_LOCATION;
    }

}
