//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.1-12/20/2010 05:40 PM(foreman)-)
//


package com.odfl.time;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "TimeLookupDelegate", targetNamespace = "http://time.odfl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimeLookupDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.odfl.time.TimeResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTT", targetNamespace = "http://time.odfl.com/", className = "com.odfl.time.GetTT")
    @ResponseWrapper(localName = "getTTResponse", targetNamespace = "http://time.odfl.com/", className = "com.odfl.time.GetTTResponse")
    @Action(input = "http://time.odfl.com/TimeLookupDelegate/getTTRequest", output = "http://time.odfl.com/TimeLookupDelegate/getTTResponse")
    public TimeResponse getTT(
        @WebParam(name = "arg0", targetNamespace = "")
        TimeRequest arg0);

}
