//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.1-12/20/2010 05:40 PM(foreman)-)
//


package com.odfl.time;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for timeResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="timeResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="delvDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="delvDay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="delvTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="destSrvCntr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orgSrvCntr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "timeResponse", propOrder = {
    "delvDate",
    "delvDay",
    "delvTime",
    "destSrvCntr",
    "message",
    "orgSrvCntr",
    "success"
})
public class TimeResponse {

    protected String delvDate;
    protected String delvDay;
    protected String delvTime;
    protected String destSrvCntr;
    protected String message;
    protected String orgSrvCntr;
    protected boolean success;

    /**
     * Gets the value of the delvDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelvDate() {
        return delvDate;
    }

    /**
     * Sets the value of the delvDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelvDate(String value) {
        this.delvDate = value;
    }

    /**
     * Gets the value of the delvDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelvDay() {
        return delvDay;
    }

    /**
     * Sets the value of the delvDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelvDay(String value) {
        this.delvDay = value;
    }

    /**
     * Gets the value of the delvTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelvTime() {
        return delvTime;
    }

    /**
     * Sets the value of the delvTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelvTime(String value) {
        this.delvTime = value;
    }

    /**
     * Gets the value of the destSrvCntr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestSrvCntr() {
        return destSrvCntr;
    }

    /**
     * Sets the value of the destSrvCntr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestSrvCntr(String value) {
        this.destSrvCntr = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the orgSrvCntr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgSrvCntr() {
        return orgSrvCntr;
    }

    /**
     * Sets the value of the orgSrvCntr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgSrvCntr(String value) {
        this.orgSrvCntr = value;
    }

    /**
     * Gets the value of the success property.
     * 
     */
    public boolean isSuccess() {
        return success;
    }

    /**
     * Sets the value of the success property.
     * 
     */
    public void setSuccess(boolean value) {
        this.success = value;
    }

}
