//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.1-12/20/2010 05:40 PM(foreman)-)
//


package com.odfl.time;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for timeRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="timeRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="billToAcct" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="destZip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orgZip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pickUpDateYMD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "timeRequest", propOrder = {
    "billToAcct",
    "destZip",
    "orgZip",
    "pickUpDateYMD"
})
public class TimeRequest {

    protected String billToAcct;
    protected String destZip;
    protected String orgZip;
    protected String pickUpDateYMD;

    /**
     * Gets the value of the billToAcct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToAcct() {
        return billToAcct;
    }

    /**
     * Sets the value of the billToAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToAcct(String value) {
        this.billToAcct = value;
    }

    /**
     * Gets the value of the destZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestZip() {
        return destZip;
    }

    /**
     * Sets the value of the destZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestZip(String value) {
        this.destZip = value;
    }

    /**
     * Gets the value of the orgZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgZip() {
        return orgZip;
    }

    /**
     * Sets the value of the orgZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgZip(String value) {
        this.orgZip = value;
    }

    /**
     * Gets the value of the pickUpDateYMD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickUpDateYMD() {
        return pickUpDateYMD;
    }

    /**
     * Sets the value of the pickUpDateYMD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickUpDateYMD(String value) {
        this.pickUpDateYMD = value;
    }

}
